name: blueberry
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  #Database
  supabase_flutter: ^2.10.3

  #fonts
  google_fonts: ^6.3.3

  # utils
  nb_utils: ^7.1.8
  ag_widgets: ^1.1.6

  # State Management
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  mobx_codegen: ^2.7.4
#  dart run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

